# Generated by Django 5.0.3 on 2024-05-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='uploads_resume')),
            ],
            options={
                'verbose_name': 'Resume',
            },
        ),
    ]
